### ISSUE TITLE
Coverage for regional sub-domains

### ISSUE THREAD

**Issue by RiaanBurger** [wtimme/firefox-remove-safelinks#6]
Mind adding:

```js
      "https://*.safelinks.protection.outlook.com/*",
```

To cover regional sub-domains like: `https://eur02.safelinks.protection.outlook.com/?url=...` please.

**Comment by wtimme** [comment]
Hey @RiaanBurger, thanks a lot for the input! Support for these regional subdomains was added with 1.5.0 (see the [changelog](https://addons.mozilla.org/en-US/firefox/addon/disable-microsoft-safe-links/versions/)), but I forgot to push the corresponding changes. I've done that now. The update is live since about a month, so these regional domains should be blocked already.

Thanks for reminding me! Glad you find the addon useful.
